### ISSUE TITLE
result of Doduo on SOTAB benchmark.

### ISSUE THREAD

**Issue by A11en0** [superctj/observatory#26]
Hi, thanks for your great work. Your contributions have been immensely helpful to me, and I find them very inspiring. I would like to inquire whether you have attempted to reproduce Doduo's performance on the SOTAB benchmark of CTA task?

**Comment by superctj** [comment]
Hi @A11en0, thank you for your inquiry and kind words! The short answer is that we didn't evaluate DODUO's performance for the SOTAB-CTA task in our experiments reported in the VLDB paper. The longer answer is that we are cleaning up the codebase and APIs and plan to release Observatory as a Python library people can easily use for finding answers to their questions like the one you have. Stay tuned!

**Comment by A11en0** [comment]
Thank you, hope everything goes well!
